# Generated by Django 4.0.4 on 2022-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.CharField(max_length=20),
        ),
    ]
